### ISSUE TITLE
Could not load backend layout

### ISSUE THREAD

**Issue by Deadwalk3r** [FriendsOfTYPO3/introduction#104]
Hello, i installed the typo3/cms-introduction theme and if I select a backend layout and save I get the following error:

![Bildschirmfoto 2023-07-16 um 22 05 28](https://github.com/FriendsOfTYPO3/introduction/assets/13485964/3b844f86-95dc-42ab-beed-1ce1d7285cfc)

**Comment by Deadwalk3r** [comment]
And my log shows me the errors too
![Bildschirmfoto 2023-07-16 um 22 08 16](https://github.com/FriendsOfTYPO3/introduction/assets/13485964/e55db87b-9179-4480-95c2-b35a06eb9ef2)

**Comment by gilbertsoft** [comment]
Hi @Deadwalk3r , I'm not able to reproduce your error. Did you setup your instance properly according the [docs](https://docs.typo3.org/p/typo3/cms-introduction/4.6/en-us/Installation.html)?
