### ISSUE TITLE
rename contactform.yaml to contactform.form.yaml

### ISSUE THREAD

**Issue by sfsmfc** [FriendsOfTYPO3/introduction#11]
After security update 8.7.17 (see https://typo3.org/security/advisory/typo3-core-sa-2018-003/), the form file name has to be end with *.form.yaml and not only *.yaml. Therefore, the file name is to rename from contactform.yaml to contactform.form.yaml

**Comment by sfsmfc** [comment]
PR https://github.com/FriendsOfTYPO3/introduction/pull/12

**Comment by lolli42** [comment]
patch has been merged meanwhile. closing issue.
