### ISSUE TITLE
Wrong Shortcut IDs

### ISSUE THREAD

**Issue by JuergenHeym** [FriendsOfTYPO3/introduction#16]
- Typo3 v9.5.0 
- Composer based install
- Introduction Package 4.0.1

Description

Move your pointer over page "Home" and observe that the backend displays "shortcut to page (id=0)".

The same is true for newly created shortcuts.

**Comment by ohader** [comment]
I an confirm this issue which seems to be a core issue. I've moved the report to the TYPO3 core issue tracker at https://forge.typo3.org/issues/86556. Let's continue there...
