### ISSUE TITLE
Speaking URLs not working

### ISSUE THREAD

**Issue by JuergenHeym** [FriendsOfTYPO3/introduction#17]
- Typo3 v9.5.0
- Composer based install
- Intro Package 4.0.1

Description:
- Site Config configured
- Speaking URLs are shown in the browsers url-line
- Top navigation shows speaking URLs
- Clicking on these URLs leads to startpage all the time

**Comment by ohader** [comment]
Configuration seems to be correct. The reason for the behavior seems to be some reverse proxy issue - settings can be provided in the install tool for `[SYS][reverseProxyIp]`. There was an additional report for DDEV setups recently with a similar scenario, please see https://forge.typo3.org/issues/86264 for further details.

**Comment by JuergenHeym** [comment]
The [SYS][reverseProxyIp] settings did not solve the problem in may case. Perhaps our reverse proxy is to wired. I close however this issue.
