### ISSUE TITLE
Typo3 Introduction Package - PowerMail - does not end with \".form.yaml\"

### ISSUE THREAD

**Issue by zwingate** [FriendsOfTYPO3/introduction#19]
*Please explain as clearly and simply as possible. I am a beginner to ALL of this.*

I am trying to use the Typo3 Introduction Package that is supplied in extensions. I have been met with an issue when it comes to the PowerMail Form. There is an error that says, "Oops, an error occurred! Code: 20190115101558b3577805" and when I went to the logs to figure out what the happened I was told this,

"Oops, an error occurred! Code: 20190115095447070f54ce ... does not end with \".form.yaml\"". in ... /Factory\/ArrayFormFactory.php:55\nStack trace:\n#0 ... /ViewHelpers\/RenderViewHelper.php(97)" etc.

How do I go about fixing this problem? Again, total noob here... 

Versions Used:
Typo3 - 8.7.22
The Official Introduction Package - 3.0.1
PowerMail - 7.1.0

**Comment by Woeler** [comment]
You can rename the file under `fileadmin/introduction/form` and rename the file from `contactform.yaml` to `contactform.form.yaml`. Then go into the backend and go to the content element of the form (in this case should be under Content Examples > Form Elements > Forms. Edit the Contactform element, go to the plugin tab and select `contactform.form.yaml`. This solved the issue for me.

**Comment by ohader** [comment]
Thanks for your feedback, I guess this one has been resolved.
