### ISSUE TITLE
Fix meta information for TER

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/introduction#20]
https://extensions.typo3.org/extension/introduction/

* The Issue link is not correct. It points to https://forge.typo3.org/projects/extension-introduction
* Information for installing with Composer is missing (compare for example [bootstrap_package](https://extensions.typo3.org/extension/bootstrap_package/)) which shows: 

![composer](https://user-images.githubusercontent.com/13206455/54596570-34bc7980-4a35-11e9-96c2-975d661bc039.png)

As introduction package is used and mentioned in official documentation (Installation & Upgrade guide, for example), I find it very important that introduction package is well maintained. 

Thank you.

Related:

* https://git-t3o.typo3.org/t3o/ter/issues/386

**Comment by sypets** [comment]
Related

* https://forge.typo3.org/issues/88940
* TYPO3-Documentation/TYPO3CMS-Guide-Installation#134

**Comment by ohader** [comment]
Thx for creating this issue
* now referenced to composer package
* now referenced to this issue tracker on GitHub
