### ISSUE TITLE
Dev-Master compatibility for T3 dev-v10 

### ISSUE THREAD

**Issue by JBlocks** [FriendsOfTYPO3/introduction#22]
The current master branch does not work with the dev-v10 (t3 core master) branch. It is not possible to install the introduction and bootstrap package inside of preconfigured distribution (t3 backend).

We need a dev-master branch for dev-v10 compatibility.

**Comment by ohader** [comment]
This seems to be working now in general - however there are still flaws, see https://github.com/FriendsOfTYPO3/introduction/issues/34
