### ISSUE TITLE
Page tree reload is necessary after installation of Introduction Package

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/introduction#26]
I have noticed, that the page tree is not reloaded after installation. The (new) pages are there, but not visible. You need to reload the page tree (or log out and log in again). 

This can be confusing. 

I would suggest to automatically reload the page tree after installing the Introduction Package.

**Comment by ohader** [comment]
It sounds more like a bug in the TYPO3 core when importing packages (`ext:extensionmanager`), doesn't it.

**Comment by gilbertsoft** [comment]
Agree, that's something which has to be fixed in the core. I also encounter this issue from time to time but not sure how to reproduce it.
