### ISSUE TITLE
Included extension realurl does not work correctly

### ISSUE THREAD

**Issue by stweil** [FriendsOfTYPO3/introduction#3]
The included extension realurl does not work: a fresh installation of TYPO3 + introduction automatically includes the realurl extension, but the resulting links in the demo show numbers instead of textual URLs. See http://cms-next.demo.typo3.org/ for an example.

A fresh installation of TYPO3 + realurl + introduction works!

**Comment by lolli42** [comment]
closing this issue: realurl has meanwhile been removed from the introduction distribution.
