### ISSUE TITLE
Package can't be installed on TYPO3 10.4.1

### ISSUE THREAD

**Issue by Atsyn** [FriendsOfTYPO3/introduction#32]
Empty Typo3 10.4.1

When I try to enable extension "The official Introduction Package"
I got exception: Too few arguments to function TYPO3\CMS\Impexp\Utility\ImportExportUtility::__construct(), 0 passed in /srv/www/.../public/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3422 and exactly 1 expected

Operating system: Unix
PHP version: 7.4.5

composer.json
`
	"require": {
		"php": "^7.4",
		"typo3/minimal": "10.4.*",
		"typo3/cms-about": "10.4.*",
		"typo3/cms-belog": "10.4.*",
		"typo3/cms-beuser": "10.4.*",
		"typo3/cms-fluid-styled-content": "10.4.*",
		"typo3/cms-form": "10.4.*",
		"typo3/cms-info": "10.4.*",
		"typo3/cms-reports": "10.4.*",
		"typo3/cms-rte-ckeditor": "10.4.*",
		"typo3/cms-setup": "10.4.*",
		"typo3/cms-sys-note": "10.4.*",
		"typo3/cms-t3editor": "10.4.*",
		"typo3/cms-tstemplate": "10.4.*",
		"typo3/cms-felogin": "10.4.*",
		"typo3/cms-scheduler": "10.4.*",
		"typo3/cms-lowlevel": "10.4.*",
		"typo3/cms-introduction": "*",
		"svewap/ws-scss": "*"
	},
`

**Comment by ThePinkOne** [comment]
Hi Atsyn,

I had the same problem and could fix it.
Check in the Extensions Manager if the Import/Export-Extension is installed. It's a requirement for the Introduction Package, so it must be there but in my environment it wasn't installed. 
Try to activate it and then activate Introduction Package. I had to sign out and sign in after the process was finished and then everything was perfectly fine.

**Comment by Atsyn** [comment]
@ThePinkOne I've already installed it.
Two bugs have been fixed:
- In a TYPO3 class **\TYPO3\CMS\Extensionmanager\Utility\InstallUtility** line: 516
Current:
`$importExportUtility = GeneralUtility::makeInstance(ImportExportUtility::class);`
Must be:
`$importExportUtility = GeneralUtility::makeInstance(ImportExportUtility::class, $this->eventDispatcher);`
- Wrong require section in a composer.json

**Comment by ohader** [comment]
Thanks for your feedback. It seems to be working now - checked with TYPO3 v10.4.13-dev with composer in DDEV environment.
