### ISSUE TITLE
Doesn't work on TYPO3 10.4.5

### ISSUE THREAD

**Issue by ameotoko** [FriendsOfTYPO3/introduction#33]
The introduction package doesn't do anything on 10.4.5, what am I doing wrong?

**Comment by ohader** [comment]
Worked for me on a v10.4.12 installation. In case the problem still exists, please share additional details, error messages and the environment you're using in combination with TYPO3 (web server, PHP version, operating system). Thx.

**Comment by ameotoko** [comment]
I think it worked out somehow, I don't remember, may be it was the docs issue, that made it unclear. I didn't see any point to post back due to lack of activity here. Anyways, I'm using different CMS now, this is no longer relevant.
