### ISSUE TITLE
Can't access the login page from the frontend 

### ISSUE THREAD

**Issue by rababfatemah** [FriendsOfTYPO3/introduction#34]
I want to access the login Page from the frontend and I'm getting an error. 

![image](https://user-images.githubusercontent.com/54703289/88936051-da276480-d29b-11ea-9b51-9f9650422b67.png)

**Comment by SamLowryMOI** [comment]
Still no solution in sight after 5 months? "Content-examples/form-elements/forms" and "content-examples/form-elements/search" also show an error (Oops, an error occurred! Code: 202011230728285f1fa8ae, Oops, an error occurred! Code: 20201123074309141a97d1). Any advice?

**Comment by ohader** [comment]
Confirmed.
* type `login` seems to use the "old" reference (AbstractPlugin vs. Extbase)
* type `form` seems to have issue as well
