### ISSUE TITLE
Support for TYPO3 11

### ISSUE THREAD

**Issue by fnagel** [FriendsOfTYPO3/introduction#38]
Having support for TYPO3 11.x would help extension authors to test and update their extensions.

**Comment by fnagel** [comment]
See this PR #37 37

**Comment by fnagel** [comment]
See this PR #41

**Comment by gilbertsoft** [comment]
> 
> 
> See this PR #41

This was sadly not the full truth. I had to fix various bugs first. Now preparing the update to Bootstrap Package 12 (#54) and the next step will be the core update.
