### ISSUE TITLE
All *.svg files in images/backendlayouts have the size of 0 B

### ISSUE THREAD

**Issue by frank65307** [FriendsOfTYPO3/introduction#39]
Dear Developers,
I am trying Typo3 10.4.15.
In my fresh installed Typo3 10.4.15, (with symlinks on Ubuntu 20.04 localhost) I installed the introduction package via "Extentions". I edited the Site - Entry Point to my folder and explored it. The Site is working, 
but on the Page "Pages" in the Frontend there are no images of the Page Layouts.
In the fileadmin/introduction/images/backendlayouts all *.svg files have the size 0 B. Also no thumbnails to see.

When I go to "Get preconfigured distribution" the first time, there is no image of any distribution.
After the Introduction Package was installed, this image is shown, but no others.

So I think there is something going wrong in Typo3 10.4.15 or the Introduction Package 4.2., or in the installation process.
Please review and try to fix it.

I tried also an installation of the Introduction Package with composer on a composer installed Typo3 10.4.15, but there is see just a few files in the ext directory, but nothing works....May be something wrong in the software and / or missing information  and documentation....Please review when possible.

I have other installations with Typo3 8 and 9 running with Introduction Package. They are OK. 

Best regards
Frank

**Comment by PhilippKuhlmay** [comment]
This doesn't solve the problem but you can find all the svgs inside the bootstrap package at https://github.com/benjaminkott/bootstrap_package/tree/master/Resources/Public/Icons/BackendLayouts.
This worked for me. Copied the files and upload them to the webserver.

**Comment by frank65307** [comment]
Thank you PhilippKuhlmay. This is a good workaround.
