### ISSUE TITLE
Not able to view the page

### ISSUE THREAD

**Issue by nkiran21** [FriendsOfTYPO3/introduction#40]
Hi there,

First time downloading Typo3 and new version10 is not rendering the page. Have included the screenshot for reference. Manual doesnt specify what site configuration has to made. Any help would be appreciated.
![typo3 error](https://user-images.githubusercontent.com/85550311/123105048-c185e700-d437-11eb-9d93-3ce26215560c.PNG)

**Comment by Wahni69** [comment]
You have to configure a site (Fuul URL prefix) under "Site Management" "Sites". Then you will see your site. That is mandatory.

**Comment by nkiran21** [comment]
thanks for the reply. its working now😊
