### ISSUE TITLE
No root page "Congratulations" in page section after installing introduction with ddev composer require typo3/cms-introduction 

### ISSUE THREAD

**Issue by gotmadwolle** [FriendsOfTYPO3/introduction#72]
Hello,
I have followed the installation instruction for using ddev but page is still not found.
Is this maybe a short-term issue?
Or is it because I am not performing extension:setup?
How does the cmd look like with ddev?
![image](https://user-images.githubusercontent.com/97067065/147989370-e1ed476e-0168-4341-9196-6907b3272b95.png)
![image](https://user-images.githubusercontent.com/97067065/147989423-de0b0cc6-a8ab-40dc-a7e2-882d543c709d.png)
I hope someone has an idea because I did not find any glue right now.

Kind regards
Wolfgang

**Comment by roemer-ag** [comment]
Good Morning - same here... I guess its been killed by "all Extensions are now activated by default" (who ever needed this).
You can't choose "Get distributed config." in the Extension-Manager-Dropdown also.

**Comment by gilbertsoft** [comment]
Since TYPO3 11.4 it's very important to run the command `extension:setup`, I guess this was not done and then no import is executed at all. See also https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html.

**Comment by gotmadwolle** [comment]
Thank gilbertsoft to reassure me that it must work.
As I was following the book "The TYPO3 Guidebook" introducing me to ddev and composer the challenge was how to execute the cli commands in ddev environment.
First I have had to make use of the typo3 console I have to install it
~/demo> ddev composer require helhum/typo3-console
Afterwards I could execute extension:setup
~/demo> ddev typo3 extension:setup
[OK] Extension(s) "core, extbase, fluid, install, recordlist, backend, frontend,       
      dashboard, fluid_styled_content, filelist, impexp, form, seo, setup, rte_ckeditor,
      belog, beuser, extensionmanager, felogin, filemetadata, indexed_search, info,     
      sys_note, t3editor, tstemplate, viewpage, bootstrap_package, introduction,        
      helhum/typo3-console" successfully set up.    
      
Maybe the "ddev composer require helhum/typo3-console" cmd was not really necessary.
Nevertheless, thanks. Now page "Congratulations" is there.

**Comment by roemer-ag** [comment]
sorry ... but wheeere so you execute extension:setup... I think im too stupid... When I try to do it in Composer it answers: bash no such command... Thank you in advance for any hint

**Comment by gilbertsoft** [comment]
> for everyone who is wondering WHERE you have to do this:
> 
>     * Composer
> 
>     * your-project/vendor/typo3/cms-cli > php typo3 extension:setup

You'd better use the binary in the vendor/bin:

`vendor/bin/typo3 extension:setup`

**Comment by gilbertsoft** [comment]
> Maybe the "ddev composer require helhum/typo3-console" cmd was not really necessary. 

With TYPO3 11.5 the TYPO3 Console is used for some database opterations only. Simple setups should not longer require it.

**Comment by kuehlschrankkiller** [comment]
Hi, as not everybody uses composer:
Same to me: there is no congratulations page. 
How to solve the problem? Thanks.

**Comment by gilbertsoft** [comment]
> Hi, as not everybody uses composer: Same to me: there is no congratulations page. How to solve the problem? Thanks.

@kuehlschrankkiller did you follow my instructions in the linked PR?
