### ISSUE TITLE
Typo3 12 core support

### ISSUE THREAD

**Issue by dgomezleon** [FriendsOfTYPO3/introduction#82]
Hi, Bitnami engineer here,

Do you plan to support typo3 core 12 in the short term? We have been shipping the `cms-introduction` extension in previous versions and we would like to release this new major version including it too.

Regards

**Comment by gilbertsoft** [comment]
Hi @dgomezleon , yes, it's already on my list. We have to make the Bootstrap Package compatible in the first place, afterwards there will be a release for the Introduction Package too.

**Comment by sypets** [comment]
bootstrap_package is available now for v12: https://packagist.org/packages/bk2k/bootstrap-package

**Comment by gilbertsoft** [comment]
Release was just done
