### ISSUE TITLE
Cleanup for v11 / v12

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/introduction#83]
_changes which are not required to support for v12, but could be fixed along the way, lower prio._

* [ ] Table sys_language was removed, can be removed from Initialisation/data.xml `<table index="sys_language"` etc. ([changelog](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html))

**Comment by gilbertsoft** [comment]
Done with the latest release
