### ISSUE TITLE
Dependency to indexed_search

### ISSUE THREAD

**Issue by lolli42** [FriendsOfTYPO3/introduction#9]
FE page Content examples -> Form elements -> Search throws an "Ooops something wrong" content element error if ext:indexed_search has not yet been manually installed by BE admin.

However, I'm not sure how well indexed_search is configured in ext:introduction, even if loaded.

Possible solutions:
* In case we don't want to make ext:introduction load ext:indexed_search by default: Change text on page and state something that the extension must be loaded in BE first if an error is shown for the content element.
* Make ext:introduction depend on ext:indexed_search in ext_emconf and composer.json to have it automatically loaded.

**Comment by psychomieze** [comment]
- ext:introduction import data depends on indexed_search (and the other extensions) - it doesn't need to depend on them in ext_emconf
- in case the introduction package is installed via composer, the dependencies were added.
