### ISSUE TITLE
Translation is wrong (data import)

### ISSUE THREAD

**Issue by markuskappe** [FriendsOfTYPO3/introduction#92]
I just created a new TYPO3 12.4.0 installation with introduction 4.6.0 (composer).
When I checked the page "Any language, any character", the page was not translated. But the content was. And the German content was in Dansk, and the Dansk content was in German.

**Comment by gilbertsoft** [comment]
Thanks for the hint. Looks like some mirgration in the past failed. We will provide a new release soon...
